export const GET_GAMES = "GET_GAMES"
export const SEARCH_BY_NAME = "SEARCH_BY_NAME"
export const ORDER_BY_NAME = "ORDER_BY_NAME"
export const ORDER_BY_RATING = "ORDER_BY_RATING"
export const ORDER_BY_PRICE = "ORDER_BY_PRICE"
export const GET_GENRES = "GET_GENRES"
export const GET_PLATFORMS = "GET_PLATFORMS"
export const FILTER_BY_PLATFORMS = "FILTER_BY_PLATFORMS"
export const FILTER_BY_GENRES = "FILTER_BY_GENRES"
export const GET_DETAIL = "GET_DETAIL"
export const CLEAR_DETAIL = "CLEAR_DETAIL"
export const GET_USERS = "GET_USERS"
export const SEARCH_BY_NAME_ERROR = "SEARCH_BY_NAME_ERROR"
export const EMAIL_USER = "EMAIL_USER"
export const ADD_FAVORITES = "ADD_FAVORITES";
export const ADD_TO_CART = "ADD_TO_CART"
export const CLEAR_CART = "CLEAR_CART"
// export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY"
// export const NT_QUANTITY = " DECREMENT_QUANTITY"
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const CHARGE_IMAGE = "CHARGE_IMAGE"


